import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Dashboard from "@/design-systems/Templates/Dashboard";
import Navbar from "@/design-systems/Molecules/NavBar";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`inter.className flex`}

      >
             <Dashboard />
             <div className="flex flex-col w-full">
             <Navbar />
        {children}
        </div>
      </body>
    </html>
  );
}
